apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - image: wil42/playground:v2
          name: playground
      ports:
        - containerPort: 8888
          name: http
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: playground-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP 
    port: 8888
    targetPort: 8888
  selector:
    app: playground

